import { useState } from 'react';
import { Play, Plus, X, Download, Cpu } from 'lucide-react';
import RegisterCard from './components/RegisterCard';
import ALUPipeline from './components/ALUPipeline';
import ErrorMagnifier from './components/ErrorMagnifier';
import ComparisonView from './components/ComparisonView';
import { FP16 } from './lib/fp16';
import { Operation, FP16Result } from './types/fp16.types';

function App() {
  const [valueA, setValueA] = useState(3.14);
  const [valueB, setValueB] = useState(2.71);
  const [operation, setOperation] = useState<Operation>('multiply');
  const [result, setResult] = useState<FP16Result | null>(null);
  const [isAnimating, setIsAnimating] = useState(false);

  const executeOperation = () => {
    setIsAnimating(true);
    setTimeout(() => {
      const fp16A = new FP16(valueA);
      const fp16B = new FP16(valueB);

      const calcResult = operation === 'multiply'
        ? FP16.multiply(fp16A, fp16B)
        : FP16.add(fp16A, fp16B);

      setResult(calcResult);
      setIsAnimating(false);
    }, 100);
  };

  const exportTraceLog = () => {
    if (!result) return;

    const log = [
      '=== FP16 Arithmetic Simulator Log ===',
      '',
      `Operation: ${operation.toUpperCase()}`,
      `Operand A: ${valueA} (${new FP16(valueA).getBits()})`,
      `Operand B: ${valueB} (${new FP16(valueB).getBits()})`,
      '',
      '--- ALU Pipeline Stages ---',
      '',
      ...result.stages.flatMap(stage => [
        `${stage.name}`,
        stage.description,
        ...stage.details.map(d => `  • ${d}`),
        '',
      ]),
      '--- Result ---',
      `Binary: ${result.bits}`,
      `Decimal: ${result.decimal}`,
      `True Math: ${result.trueMathResult}`,
      `Quantization Error: ${result.quantizationError}`,
      '',
      'Generated by FP16 Arithmetic Simulator',
    ].join('\n');

    const blob = new Blob([log], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fp16-trace-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 font-sans">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-white via-gray-50 to-gray-100"></div>

      <div className="relative">
        <header className="border-b border-gray-200 backdrop-blur-sm bg-white/80 sticky top-0 z-10 shadow-sm">
          <div className="max-w-5xl mx-auto px-4 py-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-gray-900 flex items-center justify-center text-white">
                  <Cpu className="w-6 h-6" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold text-gray-900 tracking-tight">
                    FP16 Arithmetic Simulator
                  </h1>
                  <p className="text-xs text-gray-500 font-medium">High-Fidelity Hardware Simulator</p>
                </div>
              </div>
              {result && (
                <button
                  onClick={exportTraceLog}
                  className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 hover:bg-gray-50 hover:border-gray-300 rounded-lg transition-colors text-sm font-medium text-gray-700 shadow-sm"
                >
                  <Download className="w-4 h-4" />
                  Export Trace
                </button>
              )}
            </div>
          </div>
        </header>

        <main className="max-w-5xl mx-auto px-4 py-6">
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <RegisterCard
                label="Register A"
                value={valueA}
                onChange={setValueA}
                color="indigo"
              />
              <RegisterCard
                label="Register B"
                value={valueB}
                onChange={setValueB}
                color="purple"
              />
            </div>

            <div className="bg-white border border-gray-200 shadow-sm rounded-xl p-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div className="flex gap-2">
                  <button
                    onClick={() => setOperation('add')}
                    className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-all ${
                      operation === 'add'
                        ? 'bg-gray-900 text-white shadow-sm'
                        : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
                    }`}
                  >
                    <Plus className="w-4 h-4 inline mr-1" />
                    Add
                  </button>
                  <button
                    onClick={() => setOperation('multiply')}
                    className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-all ${
                      operation === 'multiply'
                        ? 'bg-gray-900 text-white shadow-sm'
                        : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
                    }`}
                  >
                    <X className="w-4 h-4 inline mr-1" />
                    Multiply
                  </button>
                </div>
                <button
                  onClick={executeOperation}
                  disabled={isAnimating}
                  className="flex items-center justify-center gap-2 px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-semibold transition-all shadow-sm disabled:opacity-50 disabled:cursor-not-allowed w-full sm:w-auto"
                >
                  <Play className="w-4 h-4" />
                  Execute
                </button>
              </div>
            </div>

            {result && (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
                <div className="bg-white border border-gray-200 shadow-sm rounded-xl overflow-hidden">
                  <div className="p-4 border-b border-gray-100 bg-gray-50">
                    <h2 className="text-sm font-bold text-gray-900 uppercase tracking-wider flex items-center gap-2">
                      <Cpu className="w-4 h-4 text-blue-600" />
                      Hardware Execution Pipeline
                    </h2>
                  </div>
                  <ALUPipeline stages={result.stages} isAnimating={isAnimating} />
                </div>

                  <ErrorMagnifier
                    trueMath={result.trueMathResult}
                    fp16Result={result.decimal}
                    quantizationError={result.quantizationError}
                  />

                <ComparisonView result={result} />
              </div>
            )}
          </div>
        </main>

        <footer className="border-t border-gray-200 mt-8 bg-white/80 backdrop-blur-sm">
          <div className="max-w-5xl mx-auto px-4 py-4">
            <p className="text-center text-xs text-gray-500 font-medium">
              Educational hardware simulator demonstrating IEEE 754 Half-Precision floating-point arithmetic
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
}

export default App;
