import { useState } from 'react';
import { Play, Plus, X, Download, Cpu } from 'lucide-react';
import RegisterCard from './components/RegisterCard';
import ALUPipeline from './components/ALUPipeline';
import ErrorMagnifier from './components/ErrorMagnifier';
import ComparisonView from './components/ComparisonView';
import LogicLegend from './components/LogicLegend';
import { FP16 } from './lib/fp16';
import { Operation, FP16Result } from './types/fp16.types';

function App() {
  const [valueA, setValueA] = useState(3.14);
  const [valueB, setValueB] = useState(2.71);
  const [operation, setOperation] = useState<Operation>('multiply');
  const [result, setResult] = useState<FP16Result | null>(null);
  const [isAnimating, setIsAnimating] = useState(false);

  const executeOperation = () => {
    setIsAnimating(true);
    setTimeout(() => {
      const fp16A = new FP16(valueA);
      const fp16B = new FP16(valueB);

      const calcResult = operation === 'multiply'
        ? FP16.multiply(fp16A, fp16B)
        : FP16.add(fp16A, fp16B);

      setResult(calcResult);
      setIsAnimating(false);
    }, 100);
  };

  const exportTraceLog = () => {
    if (!result) return;

    const log = [
      '=== Silicon-Trace FP16 Calculation Log ===',
      '',
      `Operation: ${operation.toUpperCase()}`,
      `Operand A: ${valueA} (${new FP16(valueA).getBits()})`,
      `Operand B: ${valueB} (${new FP16(valueB).getBits()})`,
      '',
      '--- ALU Pipeline Stages ---',
      '',
      ...result.stages.flatMap(stage => [
        `${stage.name}`,
        stage.description,
        ...stage.details.map(d => `  • ${d}`),
        '',
      ]),
      '--- Result ---',
      `Binary: ${result.bits}`,
      `Decimal: ${result.decimal}`,
      `True Math: ${result.trueMathResult}`,
      `Quantization Error: ${result.quantizationError}`,
      '',
      'Generated by Silicon-Trace FP16 Simulator',
    ].join('\n');

    const blob = new Blob([log], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fp16-trace-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-900 text-white">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-900/20 via-slate-900 to-slate-900"></div>

      <div className="relative">
        <header className="border-b border-slate-800 backdrop-blur-sm bg-slate-900/50 sticky top-0 z-10">
          <div className="max-w-7xl mx-auto px-6 py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
                  <Cpu className="w-6 h-6" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">
                    Silicon-Trace FP16
                  </h1>
                  <p className="text-xs text-slate-400">High-Fidelity Hardware Simulator</p>
                </div>
              </div>
              {result && (
                <button
                  onClick={exportTraceLog}
                  className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors text-sm"
                >
                  <Download className="w-4 h-4" />
                  Export Trace
                </button>
              )}
            </div>
          </div>
        </header>

        <main className="max-w-7xl mx-auto px-6 py-8">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <RegisterCard
                  label="Register A"
                  value={valueA}
                  onChange={setValueA}
                  color="indigo"
                />
                <RegisterCard
                  label="Register B"
                  value={valueB}
                  onChange={setValueB}
                  color="purple"
                />
              </div>

              <div className="border border-slate-700 rounded-xl p-6 backdrop-blur-sm bg-slate-800/30">
                <h3 className="text-lg font-semibold mb-4">Operation Control</h3>
                <div className="flex gap-4 items-center">
                  <div className="flex gap-2">
                    <button
                      onClick={() => setOperation('add')}
                      className={`px-4 py-2 rounded-lg font-medium transition-all ${
                        operation === 'add'
                          ? 'bg-indigo-500 text-white'
                          : 'bg-slate-800 text-slate-400 hover:bg-slate-700'
                      }`}
                    >
                      <Plus className="w-4 h-4 inline mr-1" />
                      Add
                    </button>
                    <button
                      onClick={() => setOperation('multiply')}
                      className={`px-4 py-2 rounded-lg font-medium transition-all ${
                        operation === 'multiply'
                          ? 'bg-indigo-500 text-white'
                          : 'bg-slate-800 text-slate-400 hover:bg-slate-700'
                      }`}
                    >
                      <X className="w-4 h-4 inline mr-1" />
                      Multiply
                    </button>
                  </div>
                  <button
                    onClick={executeOperation}
                    disabled={isAnimating}
                    className="flex items-center gap-2 px-6 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 rounded-lg font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <Play className="w-4 h-4" />
                    Execute
                  </button>
                </div>
              </div>

              {result && (
                <>
                  <div>
                    <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
                      <span className="w-1 h-6 bg-gradient-to-b from-indigo-500 to-purple-500 rounded-full"></span>
                      ALU Pipeline Execution
                    </h2>
                    <ALUPipeline stages={result.stages} isAnimating={isAnimating} />
                  </div>

                  <ErrorMagnifier
                    trueMath={result.trueMathResult}
                    fp16Result={result.decimal}
                    quantizationError={result.quantizationError}
                  />

                  <ComparisonView result={result} />
                </>
              )}
            </div>

            <div className="lg:col-span-1">
              <LogicLegend />
            </div>
          </div>
        </main>

        <footer className="border-t border-slate-800 mt-12">
          <div className="max-w-7xl mx-auto px-6 py-6">
            <p className="text-center text-sm text-slate-500">
              Educational hardware simulator demonstrating IEEE 754 Half-Precision floating-point arithmetic
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
}

export default App;
